/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import javax.swing.DefaultListModel;
import java.util.List;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author raihanLazuardi
 */
public class FrameUtama extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameUtama.class.getName());

    MysqlMahasiswaService service;
    DefaultListModel<String> dlmId;
    DefaultListModel<String> dlmNama;

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
        service = new MysqlMahasiswaService();
        dlmId = new DefaultListModel<>();
        dlmNama = new DefaultListModel<>();
        jListId.setModel(dlmId);
        jListNama.setModel(dlmNama);

        // Sinkronisasi seleksi antara kedua list
        jListId.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int index = jListId.getSelectedIndex();
                if (index >= 0) {
                    jListNama.setSelectedIndex(index);
                    // Isi field edit dan hapus
                    jTextFieldEditId.setText(dlmId.getElementAt(index));
                    jTextFieldEditNama.setText(dlmNama.getElementAt(index));
                    jTextFieldHapusId.setText(dlmId.getElementAt(index));
                    jTextFieldHapusNama.setText(dlmNama.getElementAt(index));
                }
            }
        });

        jListNama.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int index = jListNama.getSelectedIndex();
                if (index >= 0) {
                    jListId.setSelectedIndex(index);
                    // Isi field edit dan hapus
                    jTextFieldEditId.setText(dlmId.getElementAt(index));
                    jTextFieldEditNama.setText(dlmNama.getElementAt(index));
                    jTextFieldHapusId.setText(dlmId.getElementAt(index));
                    jTextFieldHapusNama.setText(dlmNama.getElementAt(index));
                }
            }
        });
    }

    /**
     * Refresh data dari database dan tampilkan di list
     */
    private void refreshList() {
        dlmId.clear();
        dlmNama.clear();
        List<Mahasiswa> listMhs = service.getAll();
        for (Mahasiswa mhs : listMhs) {
            dlmId.addElement(String.valueOf(mhs.getId()));
            dlmNama.addElement(mhs.getNama());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneId = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jScrollPaneNama = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelHeaderId = new javax.swing.JLabel();
        jLabelHeaderNama = new javax.swing.JLabel();
        jButtonAmbilSemua = new javax.swing.JButton();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldTambahNama = new javax.swing.JTextField();
        jButtonTambahkan = new javax.swing.JButton();
        jTextFieldEditId = new javax.swing.JTextField();
        jTextFieldEditNama = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldHapusId = new javax.swing.JTextField();
        jTextFieldHapusNama = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetIndex = new javax.swing.JButton();
        jLabelResetInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelola Data Mahasiswa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPaneId.setViewportView(jListId);

        jScrollPaneNama.setViewportView(jListNama);

        jLabelHeaderId.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabelHeaderId.setText("ID");

        jLabelHeaderNama.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabelHeaderNama.setText("NAMA");

        jButtonAmbilSemua.setText("Ambil Semua Data");
        jButtonAmbilSemua.addActionListener(this::jButtonAmbilSemuaActionPerformed);

        jLabelNama.setText("nama :");

        jButtonTambahkan.setText("Tambahkan");
        jButtonTambahkan.addActionListener(this::jButtonTambahkanActionPerformed);

        jTextFieldEditId.setEditable(false);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jTextFieldHapusId.setEditable(false);

        jTextFieldHapusNama.setEditable(false);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonResetIndex.setText("Reset indeks");
        jButtonResetIndex.addActionListener(this::jButtonResetIndexActionPerformed);

        jLabelResetInfo.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHeaderId)
                    .addComponent(jScrollPaneId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHeaderNama)
                    .addComponent(jScrollPaneNama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAmbilSemua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNama)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldTambahNama)
                    .addComponent(jButtonTambahkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldHapusId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonResetIndex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelResetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHeaderId)
                            .addComponent(jLabelHeaderNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneId, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jScrollPaneNama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAmbilSemua)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTambahkan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHapusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndex)
                            .addComponent(jLabelResetInfo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilSemuaActionPerformed
        refreshList();
    }//GEN-LAST:event_jButtonAmbilSemuaActionPerformed

    private void jButtonTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahkanActionPerformed
        String nama = jTextFieldTambahNama.getText().trim();
        if (!nama.isEmpty()) {
            Mahasiswa mhs = new Mahasiswa();
            mhs.setNama(nama);
            service.add(mhs);
            refreshList();
        }
    }//GEN-LAST:event_jButtonTambahkanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String idStr = jTextFieldEditId.getText().trim();
        String nama = jTextFieldEditNama.getText().trim();
        if (!idStr.isEmpty() && !nama.isEmpty()) {
            int id = Integer.parseInt(idStr);
            Mahasiswa mhs = new Mahasiswa(id, nama);
            service.update(mhs);
            refreshList();
            jTextFieldEditId.setText("");
            jTextFieldEditNama.setText("");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        String idStr = jTextFieldHapusId.getText().trim();
        if (!idStr.isEmpty()) {
            int id = Integer.parseInt(idStr);
            service.delete(id);
            refreshList();
            jTextFieldHapusId.setText("");
            jTextFieldHapusNama.setText("");
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonResetIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndexActionPerformed
        service.indexReset();
        refreshList();
        jLabelResetInfo.setText("Index di reset ke 0");
    }//GEN-LAST:event_jButtonResetIndexActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        service.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilSemua;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonResetIndex;
    private javax.swing.JButton jButtonTambahkan;
    private javax.swing.JLabel jLabelHeaderId;
    private javax.swing.JLabel jLabelHeaderNama;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelResetInfo;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPaneId;
    private javax.swing.JScrollPane jScrollPaneNama;
    private javax.swing.JTextField jTextFieldEditId;
    private javax.swing.JTextField jTextFieldEditNama;
    private javax.swing.JTextField jTextFieldHapusId;
    private javax.swing.JTextField jTextFieldHapusNama;
    private javax.swing.JTextField jTextFieldTambahNama;
    // End of variables declaration//GEN-END:variables
}
